#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
command -v shellcheck >/dev/null && shellcheck "$0"

for dir in slinky noble-cctp ; do
  rm -rf "proto/$dir"
  mkdir -p "proto/$dir"
  echo "Autogenerated folder, see export_protos.sh" > "proto/$dir/README.md"

  buf export "proto/$dir-src/proto" --output "proto/$dir"
done
