name: "[v4-client-js] Lint, Build, & Test"
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'v4-client-js/**'
  push:
    paths:
      - 'v4-client-js/**'
    branches:
      - main
      - "release/*"

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./v4-client-js
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js 20.8.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
          registry-url: https://registry.npmjs.org
          cache: "npm"
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}

      - name: Run eslint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
